name: Deploy

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  Deploy:
    runs-on: ubuntu-latest

    if: "! contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pnpm install

      - name: Blocklet workflow
        uses: blocklet/action-workflow@v1
        with:
          skip-upload: false
          skip-deploy: false
          bundle-command: yarn bundle
          store-endpoint: ${{ secrets.STORE_ENDPOINT }}
          store-access-token: ${{ secrets.STORE_ACCESS_TOKEN }}
          server-endpoint: ${{ secrets.SERVER_ENDPOINT }}
          server-access-key: ${{ secrets.SERVER_ACCESS_KEY }}
          server-access-secret: ${{ secrets.SERVER_ACCESS_SECRET }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
